name: Publish to Nuget
on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
jobs:
  publish:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Build
      run: docker build --target build .
    - name: Test
      run: docker build --target test .
    - name: Pack & Publish
      run: docker build --target pack-and-push --build-arg PackageVersion=${{github.ref_name}} --build-arg NuGetApiKey=${{secrets.NUGET_API_KEY}} .

